/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jimulabs.samples.timely;

public final class R {
    public static final class anim {
        public static final int dialog_enter=0x7f040000;
        public static final int dialog_exit=0x7f040001;
    }
    public static final class attr {
        /** <p>Must be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int alarmListPosition=0x7f010001;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f01000b;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f01000c;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f01000d;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f01000e;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f01000f;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int clockFontSize=0x7f010007;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int direction=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int icon=0x7f010024;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int isDream=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int isLeft=0x7f010023;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f01000a;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int overwritePage=0x7f010004;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>shake_it</code></td><td>0</td><td></td></tr>
<tr><td><code>analog_clock_background</code></td><td>1</td><td></td></tr>
<tr><td><code>analog_clock_foreground</code></td><td>2</td><td></td></tr>
<tr><td><code>analog_clock_knob</code></td><td>3</td><td></td></tr>
<tr><td><code>analog_clock_hour</code></td><td>4</td><td></td></tr>
<tr><td><code>analog_clock_minutes</code></td><td>5</td><td></td></tr>
<tr><td><code>analog_clock_second</code></td><td>6</td><td></td></tr>
<tr><td><code>app_icon</code></td><td>8</td><td></td></tr>
</table>
         */
        public static final int resource=0x7f010018;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int samplingPage=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int showBackground=0x7f010002;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int showBorder=0x7f010003;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int showDate=0x7f010006;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int showSeconds=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int switchGlowDistance=0x7f010021;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int switchMinWidth=0x7f01001f;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int switchPadding=0x7f010020;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int switchTextAppearance=0x7f01001e;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int textOff=0x7f01001c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int textOn=0x7f01001b;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int thumb=0x7f010019;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int thumbMinWidth=0x7f010022;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int thumbTextPadding=0x7f01001d;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int track=0x7f01001a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010010;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f010011;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f010012;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f010013;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f010014;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f010015;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f010016;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f010017;
    }
    public static final class color {
        public static final int separator_background=0x7f060000;
        public static final int share_inactive_background=0x7f060001;
        public static final int sku_inactive_pressed_color=0x7f060002;
        public static final int sku_item_description=0x7f060003;
        public static final int sku_item_inactive_background=0x7f060004;
        public static final int sku_item_inactive_price=0x7f060005;
        public static final int sku_item_inactive_text=0x7f060006;
        public static final int sku_item_title_checked=0x7f060007;
    }
    public static final class dimen {
        public static final int about_logo_size=0x7f070000;
        public static final int action_bar_height=0x7f070001;
        /**  Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively). 
         */
        public static final int activity_horizontal_margin=0x7f0700ec;
        public static final int add_view_height=0x7f070002;
        public static final int additional_am_pm_width=0x7f070003;
        public static final int alarm_detail_padding_bottom=0x7f070004;
        public static final int alarm_detail_padding_left=0x7f070005;
        public static final int alarm_detail_padding_right=0x7f070006;
        public static final int alarm_detail_padding_top=0x7f070007;
        public static final int alarm_list_padding_bottom=0x7f070008;
        public static final int alarm_list_padding_top=0x7f070009;
        public static final int alarm_list_undo_bar_padding=0x7f07000a;
        public static final int analog_clock_border_width=0x7f07000b;
        public static final int analog_clock_view_fancy_height_position_factor=0x7f07000c;
        public static final int analog_clock_view_height_position_factor=0x7f07000d;
        public static final int card_cut_distance=0x7f07000e;
        public static final int card_displacement=0x7f07000f;
        public static final int card_glow_distance=0x7f070010;
        public static final int card_height=0x7f070011;
        public static final int card_margin=0x7f070012;
        public static final int card_radius=0x7f070013;
        public static final int card_view_alpha_fade_height=0x7f070014;
        public static final int card_width=0x7f070015;
        public static final int challenge_container_bottom_padding=0x7f070016;
        public static final int challenge_container_height=0x7f070017;
        public static final int challenge_preview_bottom_padding=0x7f070018;
        public static final int challenge_preview_middle_padding=0x7f070019;
        public static final int challenge_preview_subtitle_size=0x7f07001a;
        public static final int challenge_preview_title_size=0x7f07001b;
        public static final int challenge_preview_top_padding=0x7f07001c;
        public static final int checkbox_padding=0x7f07001d;
        public static final int clock_max_am_pm_width=0x7f07001e;
        public static final int clock_padding_bottom=0x7f07001f;
        public static final int clock_padding_side=0x7f070020;
        public static final int clock_padding_top=0x7f070021;
        public static final int clock_view_hour_height=0x7f070022;
        public static final int clock_view_minute_height=0x7f070023;
        public static final int clock_view_ms_height=0x7f070024;
        public static final int clock_view_seconds_height=0x7f070025;
        public static final int cloud_indicator_big_indent=0x7f070026;
        public static final int cloud_indicator_small_indent=0x7f070027;
        public static final int collapsed_color_picker_padding_border=0x7f070028;
        public static final int color_picker_real_size=0x7f070029;
        public static final int color_picker_size=0x7f07002a;
        public static final int date_size=0x7f07002b;
        public static final int daydream_clock_padding_top=0x7f07002c;
        public static final int default_clock_text_size=0x7f07002d;
        public static final int dialog_light_line_top_padding=0x7f07002e;
        public static final int dialog_margins=0x7f07002f;
        public static final int dialog_round_radius=0x7f070030;
        public static final int dialog_title_height=0x7f070031;
        public static final int digital_clock_view_height_position_factor=0x7f070032;
        public static final int dismiss_bar_text_size=0x7f070033;
        public static final int dismiss_fence_cut_off_padding=0x7f070034;
        public static final int dismiss_fence_fade_out_padding=0x7f070035;
        public static final int dismiss_fence_padding=0x7f070036;
        public static final int dismiss_fence_width=0x7f070037;
        public static final int dismiss_handle_delta_y=0x7f070038;
        public static final int dismiss_handle_displacement_y=0x7f070039;
        public static final int dismiss_handle_height=0x7f07003a;
        public static final int dismiss_handle_padding=0x7f07003b;
        public static final int dismiss_text_padding_bottom=0x7f07003c;
        public static final int divider_height=0x7f07003d;
        public static final int draw_pattern_large_circle_radius=0x7f07003e;
        public static final int draw_pattern_line_width=0x7f07003f;
        public static final int draw_pattern_small_circle_radius=0x7f070040;
        public static final int draw_pattern_stroke_width=0x7f070041;
        public static final int edge_slop=0x7f070042;
        public static final int edit_text_horizontal_padding=0x7f070043;
        public static final int kerning_hack=0x7f070044;
        public static final int lap_font_size=0x7f070045;
        public static final int manage_device_drawable_padding=0x7f070046;
        public static final int manage_device_item_edit_text_padding=0x7f070047;
        public static final int manage_device_item_edit_text_padding_with_local=0x7f070048;
        public static final int manage_device_item_negative_drawable_padding=0x7f070049;
        public static final int match_challenge_circle_stroke_width=0x7f07004a;
        public static final int match_challenge_forms_margin=0x7f07004b;
        public static final int match_challenge_margin=0x7f07004c;
        public static final int math_challenge_button_height=0x7f07004d;
        public static final int math_challenge_button_padding=0x7f07004e;
        public static final int math_challenge_button_text_size=0x7f07004f;
        public static final int math_challenge_button_width=0x7f070050;
        public static final int math_challenge_line_length=0x7f070051;
        public static final int math_challenge_line_width=0x7f070052;
        public static final int math_challenge_question_text_size=0x7f070053;
        public static final int math_challenge_text_bottom_padding=0x7f070054;
        public static final int max_shop_height=0x7f070055;
        public static final int message_action_icon_padding=0x7f070056;
        public static final int message_action_padding_left=0x7f070057;
        public static final int message_container_padding_base=0x7f070058;
        public static final int message_maximum_width=0x7f070059;
        public static final int message_padding_side=0x7f07005a;
        public static final int message_vertical_padding=0x7f07005b;
        public static final int min_swipe_velocity_per_second=0x7f07005c;
        public static final int min_width_center_ad=0x7f07005d;
        public static final int next_alarm_horizontal_correction=0x7f07005e;
        public static final int next_alarm_padding=0x7f07005f;
        public static final int next_alarm_size=0x7f070060;
        public static final int notes_weekday_font_size=0x7f070061;
        public static final int on_off_delegate_padding=0x7f070062;
        public static final int padding_bottom=0x7f070063;
        public static final int padding_top=0x7f070064;
        public static final int popup_correction_bottom=0x7f070065;
        public static final int popup_correction_top=0x7f070066;
        public static final int popup_inset_bottom=0x7f070067;
        public static final int popup_inset_left=0x7f070068;
        public static final int popup_inset_right=0x7f070069;
        public static final int popup_inset_top=0x7f07006a;
        public static final int preference_empty_area_width=0x7f07006b;
        public static final int preference_fragment_padding_bottom=0x7f07006c;
        public static final int preference_fragment_padding_side=0x7f07006d;
        public static final int preference_icon_minWidth=0x7f07006e;
        public static final int preference_item_padding_inner=0x7f07006f;
        public static final int preference_item_padding_side=0x7f070070;
        public static final int preference_list_padding_top=0x7f070071;
        public static final int preference_screen_bottom_margin=0x7f070072;
        public static final int preference_screen_side_margin=0x7f070073;
        public static final int preference_screen_side_margin_negative=0x7f070074;
        public static final int preference_screen_top_margin=0x7f070075;
        public static final int preference_widget_width=0x7f070076;
        public static final int purchase_dialog_buy_min_width=0x7f070077;
        public static final int rays_center=0x7f070078;
        public static final int referral_code_error_translation=0x7f070079;
        public static final int seperator_collapsed_margin_left_right=0x7f07007a;
        public static final int seperator_collapsed_margin_top=0x7f07007b;
        public static final int shake_distance=0x7f07007c;
        public static final int share_grid_spacing=0x7f07007d;
        public static final int smart_rise_rays_center_distance=0x7f07007e;
        public static final int smart_rise_rays_distance=0x7f07007f;
        public static final int smart_rise_sun_distance=0x7f070080;
        public static final int snooze_circle_distance_inbetween=0x7f070081;
        public static final int snooze_circle_effect_padding=0x7f070082;
        public static final int snooze_circle_growth=0x7f070083;
        public static final int snooze_circle_width=0x7f070084;
        public static final int snooze_clock_label_margin_bottom=0x7f070085;
        public static final int snooze_clock_margin_top=0x7f070086;
        public static final int snooze_clock_size=0x7f070087;
        public static final int snooze_inner_padding_to_button=0x7f070088;
        public static final int snooze_line_circle_length=0x7f070089;
        public static final int snooze_line_circle_width=0x7f07008a;
        public static final int snooze_text_size=0x7f07008b;
        public static final int snooze_text_size_small=0x7f07008c;
        public static final int snooze_until_text_offset=0x7f07008d;
        public static final int sound_collapsed_size=0x7f07008e;
        public static final int stopwatch_bottom_padding=0x7f07008f;
        public static final int stopwatch_drag_handle_padding=0x7f070090;
        public static final int stopwatch_drag_handle_radius=0x7f070091;
        public static final int stopwatch_hour_padding=0x7f070092;
        public static final int stopwatch_line_default_gap_size=0x7f070093;
        public static final int stopwatch_line_max_millisecond_height=0x7f070094;
        public static final int stopwatch_line_max_second_height=0x7f070095;
        public static final int stopwatch_line_min_height=0x7f070096;
        public static final int stopwatch_line_quarter_length=0x7f070097;
        public static final int stopwatch_list_padding_bottom=0x7f070098;
        public static final int stopwatch_max_lap_gap_width=0x7f070099;
        public static final int stopwatch_padding=0x7f07009a;
        public static final int stopwatch_padding_clock=0x7f07009b;
        public static final int stopwatch_padding_top_list=0x7f07009c;
        public static final int stopwatch_seconds_width=0x7f07009d;
        public static final int stopwatch_smal_time_arc_width=0x7f07009e;
        public static final int stopwatch_text_padding=0x7f07009f;
        public static final int stopwatch_time_arc_width=0x7f0700a0;
        public static final int stopwatch_time_text_size=0x7f0700a1;
        public static final int stopwatch_timer_automatic_rotation_velocity=0x7f0700a2;
        public static final int stopwatch_timer_min_distance_for_fling=0x7f0700a3;
        public static final int stopwatch_timer_min_fling_velocity=0x7f0700a4;
        public static final int stopwatch_timer_min_swipe_velocity=0x7f0700a5;
        public static final int stopwatch_timer_title_size=0x7f0700a6;
        public static final int switch_collapsed_margin_top=0x7f0700a7;
        public static final int switch_expanded_margin_top=0x7f0700a8;
        public static final int tab_bar_height=0x7f0700a9;
        public static final int tab_indicator_height=0x7f0700aa;
        public static final int tablet_tab_width=0x7f0700ab;
        public static final int theme_creation_colapsed_size=0x7f0700ac;
        public static final int theme_creation_color_border=0x7f0700ad;
        public static final int theme_pack_font_size=0x7f0700ae;
        public static final int theme_pack_icon_padding=0x7f0700af;
        public static final int theme_page_Indicator_collapsed_size=0x7f0700b0;
        public static final int theme_page_Indicator_expanded_size=0x7f0700b1;
        public static final int theme_page_indicator_margin_top=0x7f0700b2;
        public static final int theme_page_indicator_padding=0x7f0700b3;
        public static final int theme_page_indicator_scroll_amount=0x7f0700b4;
        public static final int theme_preview_border=0x7f0700b5;
        public static final int theme_preview_border_active=0x7f0700b6;
        public static final int theme_selection_item_size=0x7f0700b7;
        public static final int theme_selection_item_size_with_padding=0x7f0700b8;
        public static final int theme_selection_packet_padding=0x7f0700b9;
        public static final int theme_selection_padding=0x7f0700ba;
        public static final int theme_selection_total_packet_height=0x7f0700bb;
        public static final int theme_selection_undo_bar_padding=0x7f0700bc;
        public static final int time_bar_font_size=0x7f0700bd;
        public static final int time_font_size=0x7f0700be;
        public static final int time_font_size_collapsed=0x7f0700bf;
        public static final int time_glow_distance=0x7f0700c0;
        public static final int time_glow_margin_collapsed=0x7f0700c1;
        public static final int timeline_font_margin=0x7f0700c2;
        public static final int timeline_line_thickness=0x7f0700c3;
        public static final int timeline_list_bottom_padding=0x7f0700c4;
        public static final int timeline_list_top_padding=0x7f0700c5;
        public static final int timeline_margin_top_bottom=0x7f0700c6;
        public static final int timeline_max_font_size=0x7f0700c7;
        public static final int timeline_max_line_length=0x7f0700c8;
        public static final int timeline_min_line_length=0x7f0700c9;
        public static final int timeline_set_time_top_padding=0x7f0700ca;
        public static final int timeline_shadow_offset=0x7f0700cb;
        public static final int timeline_width=0x7f0700cc;
        public static final int timer_drag_handle_height=0x7f0700cd;
        public static final int timer_drag_handle_width=0x7f0700ce;
        public static final int timer_stopwatch_buttons_factor=0x7f0700cf;
        public static final int timer_stopwatch_title_fraction=0x7f0700d0;
        public static final int toast_padding=0x7f0700d1;
        public static final int tutorial_challenge_preview_offset_y=0x7f0700d2;
        public static final int tutorial_set_exact_time_hand_offset_y=0x7f0700d3;
        public static final int tutorial_set_exact_time_text_offset_y=0x7f0700d4;
        public static final int tutorial_swipe_hand_offset_x=0x7f0700d5;
        public static final int tutorial_tap_bottom_padding=0x7f0700d6;
        public static final int tutorial_tap_circle_radius=0x7f0700d7;
        public static final int tutorial_tap_circle_stroke_width=0x7f0700d8;
        public static final int tutorial_tap_hand_x_offset=0x7f0700d9;
        public static final int tutorial_tap_hand_y_offset=0x7f0700da;
        public static final int tutorial_tap_padding=0x7f0700db;
        public static final int tutorial_tap_tip_x=0x7f0700dc;
        public static final int tutorial_tap_tip_y=0x7f0700dd;
        public static final int underline_height=0x7f0700de;
        public static final int unlock_padding=0x7f0700df;
        public static final int unlock_padding_themes=0x7f0700e0;
        public static final int welcome_app_icon_size=0x7f0700e1;
        public static final int welcome_header_size=0x7f0700e2;
        public static final int welcome_header_text_size=0x7f0700e3;
        public static final int widget_alarm_padding=0x7f0700e4;
        public static final int widget_alarm_padding_top=0x7f0700e5;
        public static final int widget_date_margin_top=0x7f0700e6;
        public static final int widget_date_margin_top_single_line=0x7f0700e7;
        public static final int widget_min_height=0x7f0700e8;
        public static final int widget_min_resize_height=0x7f0700e9;
        public static final int widget_min_resize_width=0x7f0700ea;
        public static final int widget_min_width=0x7f0700eb;
    }
    public static final class drawable {
        public static final int action_bar_background=0x7f020000;
        public static final int add_theme_button=0x7f020001;
        public static final int alarm_icon=0x7f020002;
        public static final int alarm_icon_inactive=0x7f020003;
        public static final int alarm_small=0x7f020004;
        public static final int analog_clock_filtered_background_281_294=0x7f020005;
        public static final int analog_clock_filtered_background_422_442=0x7f020006;
        public static final int analog_clock_filtered_background_562_588=0x7f020007;
        public static final int analog_clock_filtered_background_843_882=0x7f020008;
        public static final int analog_clock_handle_hour_19_95=0x7f020009;
        public static final int analog_clock_handle_hour_28_140=0x7f02000a;
        public static final int analog_clock_handle_hour_38_190=0x7f02000b;
        public static final int analog_clock_handle_hour_57_284=0x7f02000c;
        public static final int analog_clock_handle_minute_19_151=0x7f02000d;
        public static final int analog_clock_handle_minute_29_231=0x7f02000e;
        public static final int analog_clock_handle_minute_38_303=0x7f02000f;
        public static final int analog_clock_handle_minute_57_454=0x7f020010;
        public static final int analog_clock_handle_second_10_150=0x7f020011;
        public static final int analog_clock_handle_second_15_225=0x7f020012;
        public static final int analog_clock_handle_second_21_300=0x7f020013;
        public static final int analog_clock_handle_second_31_450=0x7f020014;
        public static final int analog_clock_handles_knob_16_16=0x7f020015;
        public static final int analog_clock_handles_knob_25_25=0x7f020016;
        public static final int analog_clock_handles_knob_36_36=0x7f020017;
        public static final int analog_clock_handles_knob_49_49=0x7f020018;
        public static final int analog_clock_highlights_281_294=0x7f020019;
        public static final int analog_clock_highlights_422_442=0x7f02001a;
        public static final int analog_clock_highlights_562_588=0x7f02001b;
        public static final int analog_clock_highlights_843_882=0x7f02001c;
        public static final int app_icon_128=0x7f02001d;
        public static final int app_icon_180=0x7f02001e;
        public static final int app_icon_240=0x7f02001f;
        public static final int app_icon_360=0x7f020020;
        public static final int app_icon_600=0x7f020021;
        public static final int app_icon_64=0x7f020022;
        public static final int app_icon_96=0x7f020023;
        public static final int background_overflow_inset=0x7f020024;
        public static final int beam=0x7f020025;
        public static final int bg_blue_gradient=0x7f020026;
        public static final int bg_cyan_gradient=0x7f020027;
        public static final int bg_orange_gradient=0x7f020028;
        public static final int card_background=0x7f020029;
        public static final int card_detail_background_nine_patch=0x7f02002a;
        public static final int challenge_icon=0x7f02002b;
        public static final int checkbox_checked=0x7f02002c;
        public static final int checkbox_unchecked=0x7f02002d;
        public static final int circle_effect=0x7f02002e;
        public static final int clock_face_icon=0x7f02002f;
        public static final int cloud_notifier_big_off=0x7f020030;
        public static final int cloud_notifier_big_on=0x7f020031;
        public static final int cloud_notifier_small_off=0x7f020032;
        public static final int cloud_notifier_small_on=0x7f020033;
        public static final int colorable_checkbox=0x7f020034;
        public static final int colorable_seek_bar=0x7f020035;
        public static final int content_new_dark=0x7f020036;
        public static final int crash_android_crop=0x7f020037;
        public static final int cut_effect=0x7f020038;
        public static final int dark_background=0x7f0200b6;
        public static final int dialog_full_holo_light=0x7f020039;
        public static final int dialog_template=0x7f02003a;
        public static final int discount=0x7f02003b;
        public static final int dismiss_arrow=0x7f02003c;
        public static final int dismiss_docked_arrows=0x7f02003d;
        public static final int dismiss_drag_icon=0x7f02003e;
        public static final int dismiss_handle_drag_glow=0x7f02003f;
        public static final int dot_mask=0x7f020040;
        public static final int drag_handle=0x7f020041;
        public static final int edit_icon=0x7f020042;
        public static final int expand_bar=0x7f020043;
        public static final int expand_button_background=0x7f020044;
        public static final int expand_button_background_focused=0x7f0200b7;
        public static final int expand_button_background_pressed=0x7f0200b8;
        public static final int expand_symbol=0x7f020045;
        public static final int expandable_edit_text_background=0x7f020046;
        public static final int fb_icon=0x7f020047;
        public static final int hand=0x7f020048;
        public static final int holiday_ad=0x7f020049;
        public static final int ic_backspace=0x7f02004a;
        public static final int ic_backspace_disabled=0x7f02004b;
        public static final int ic_backspace_normal=0x7f02004c;
        public static final int ic_extension_next_alarm=0x7f02004d;
        public static final int ic_launcher=0x7f02004e;
        public static final int ic_menu_accept=0x7f02004f;
        public static final int ic_menu_add_alarm=0x7f020050;
        public static final int ic_menu_cancel=0x7f020051;
        public static final int ic_menu_delete=0x7f020052;
        public static final int ic_menu_overflow=0x7f020053;
        public static final int ic_menu_overflow_small=0x7f020054;
        public static final int ic_menu_timer=0x7f020055;
        public static final int ic_tab_alarm=0x7f020056;
        public static final int ic_tab_stopwatch=0x7f020057;
        public static final int ic_tab_time=0x7f020058;
        public static final int ic_undobar_undo=0x7f020059;
        public static final int info_icon=0x7f02005a;
        public static final int inhouse_ad=0x7f02005b;
        public static final int list_section_divider_holo_dark=0x7f02005c;
        public static final int match_preview=0x7f02005d;
        public static final int math_challenge=0x7f02005e;
        public static final int message_bar_button_center=0x7f02005f;
        public static final int message_bar_center_button_focused=0x7f020060;
        public static final int message_bar_center_button_pressed=0x7f020061;
        public static final int next_alarm_icon=0x7f020062;
        public static final int no_challange_icon=0x7f020063;
        public static final int no_sound_icon=0x7f020064;
        public static final int notification_icon=0x7f020065;
        public static final int onoff_background=0x7f020066;
        public static final int onoff_background_blue=0x7f020067;
        public static final int onoff_thumb=0x7f020068;
        public static final int onoff_thumb_blue=0x7f020069;
        public static final int onoff_thumb_enabled=0x7f02006a;
        public static final int onoff_thumb_enabled_blue=0x7f02006b;
        public static final int onoff_thumb_selector=0x7f02006c;
        public static final int open_card_indicator=0x7f02006d;
        public static final int pattern_challenge=0x7f02006e;
        public static final int pause_icon=0x7f02006f;
        public static final int phone_icon=0x7f020070;
        public static final int phone_icon_small=0x7f020071;
        public static final int picker_selection=0x7f020072;
        public static final int plus_icon=0x7f020073;
        public static final int popup_background=0x7f020074;
        public static final int premium_banner=0x7f020075;
        public static final int premium_corner_100_100=0x7f020076;
        public static final int premium_corner_150_150=0x7f020077;
        public static final int premium_corner_200_200=0x7f020078;
        public static final int premium_corner_300_300=0x7f020079;
        public static final int premium_huge=0x7f02007a;
        public static final int premium_icon=0x7f02007b;
        public static final int premium_large=0x7f02007c;
        public static final int press_background=0x7f0200b9;
        public static final int press_background_darker=0x7f0200ba;
        public static final int press_background_light=0x7f0200bb;
        public static final int press_background_stronger=0x7f0200bc;
        public static final int radio_button=0x7f02007d;
        public static final int radio_button_off=0x7f02007e;
        public static final int radio_button_on=0x7f02007f;
        public static final int referals_icon=0x7f020080;
        public static final int scrubber_control_focused_holo=0x7f020081;
        public static final int scrubber_control_normal_holo=0x7f020082;
        public static final int scrubber_control_pressed_holo=0x7f020083;
        public static final int scrubber_primary_holo=0x7f020084;
        public static final int scrubber_thumb_holo=0x7f020085;
        public static final int scrubber_track_holo_dark=0x7f020086;
        public static final int shake_it_150=0x7f020087;
        public static final int shake_it_225=0x7f020088;
        public static final int shake_it_300=0x7f020089;
        public static final int shake_it_450=0x7f02008a;
        public static final int shake_preview=0x7f02008b;
        public static final int smart_rise_background=0x7f02008c;
        public static final int smart_rise_rays=0x7f02008d;
        public static final int smart_rise_sun=0x7f02008e;
        public static final int snooze_button_highligh_bottom=0x7f02008f;
        public static final int snooze_button_highligh_top=0x7f020090;
        public static final int snooze_glow=0x7f020091;
        public static final int snooze_icon=0x7f020092;
        public static final int social_media_button_press=0x7f020093;
        public static final int sound_icon=0x7f020094;
        public static final int sound_small=0x7f020095;
        public static final int stop_watch=0x7f020096;
        public static final int stop_watch_action_lap=0x7f020097;
        public static final int stop_watch_action_reset=0x7f020098;
        public static final int stop_watch_action_start=0x7f020099;
        public static final int stop_watch_action_stop=0x7f02009a;
        public static final int stop_watch_inactive=0x7f02009b;
        public static final int stop_watch_notification_icon=0x7f02009c;
        public static final int stop_watch_pause_background=0x7f02009d;
        public static final int stop_watch_start_background=0x7f02009e;
        public static final int stop_watch_stop_background=0x7f02009f;
        public static final int stopwatch_button_background=0x7f0200a0;
        public static final int stopwatch_button_press_background=0x7f0200bd;
        public static final int stopwatch_timer_start_stop_background=0x7f0200a1;
        public static final int tab_button=0x7f0200a2;
        public static final int tab_button_dark=0x7f0200a3;
        public static final int textfield_default_holo_dark=0x7f0200a4;
        public static final int textfield_empty_background=0x7f0200a5;
        public static final int theme_add_button=0x7f0200a6;
        public static final int theme_header=0x7f0200a7;
        public static final int theme_header_button=0x7f0200a8;
        public static final int theme_header_pressed=0x7f0200a9;
        public static final int theme_pack_background_color=0x7f0200be;
        public static final int time_icon=0x7f0200aa;
        public static final int time_icon_inactive=0x7f0200ab;
        public static final int timer_add_lap_background=0x7f0200ac;
        public static final int timer_notification_icon=0x7f0200ad;
        public static final int twitter_icon=0x7f0200ae;
        public static final int undobar=0x7f0200af;
        public static final int undobar_button=0x7f0200b0;
        public static final int undobar_button_focused=0x7f0200b1;
        public static final int undobar_button_pressed=0x7f0200b2;
        public static final int up=0x7f0200b3;
        public static final int warning=0x7f0200b4;
        public static final int welcomeDivider=0x7f0200bf;
        public static final int welcomeDividerTop=0x7f0200c0;
        public static final int widget_preview=0x7f0200b5;
    }
    public static final class id {
        public static final int action_settings=0x7f050018;
        public static final int alarmList=0x7f050014;
        public static final int analog_clock_background=0x7f050006;
        public static final int analog_clock_foreground=0x7f050007;
        public static final int analog_clock_hour=0x7f050009;
        public static final int analog_clock_knob=0x7f050008;
        public static final int analog_clock_minutes=0x7f05000a;
        public static final int analog_clock_second=0x7f05000b;
        public static final int app_icon=0x7f05000c;
        public static final int cloud1=0x7f050013;
        public static final int cloud2=0x7f050012;
        public static final int cloud3=0x7f050011;
        public static final int date=0x7f050017;
        public static final int hoursMinutes=0x7f050015;
        public static final int hybrid=0x7f050004;
        public static final int none=0x7f050000;
        public static final int normal=0x7f050001;
        public static final int pager=0x7f05000d;
        public static final int satellite=0x7f050002;
        public static final int seconds=0x7f050016;
        public static final int seperator=0x7f050010;
        public static final int shake_it=0x7f050005;
        public static final int terrain=0x7f050003;
        public static final int time=0x7f05000e;
        public static final int timeSwitch=0x7f05000f;
    }
    public static final class integer {
        public static final int broadcast_port=0x7f080000;
        public static final int config_activityDefaultDur=0x7f080001;
        public static final int config_activityShortDur=0x7f080002;
        public static final int device_class=0x7f080003;
        public static final int ga_dispatchPeriod=0x7f080004;
        public static final int tablet_alarm_container_weight_sum=0x7f080005;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int alarm_list_item=0x7f030001;
        public static final int fragment_alarm_list=0x7f030002;
        public static final int fragment_clock=0x7f030003;
        public static final int fragment_stopwatch=0x7f030004;
        public static final int spacer=0x7f030005;
    }
    public static final class menu {
        public static final int main=0x7f0b0000;
    }
    public static final class string {
        public static final int action_settings=0x7f090002;
        public static final int app_name=0x7f090000;
        public static final int hello_world=0x7f090001;
        public static final int switch_off=0x7f090004;
        public static final int switch_on=0x7f090003;
    }
    public static final class style {
        public static final int ActionBar=0x7f0a0002;
        public static final int ActionBarTab=0x7f0a0003;
        public static final int AlarmScroll=0x7f0a0000;
        /** <item name="android:checkBoxPreferenceStyle">@style/CheckBoxPreference</item>
<item name="android:background">@null</item>
<item name="android:windowActionBar">false</item>
         */
        public static final int AppTheme=0x7f0a0001;
        public static final int AreaSeparator=0x7f0a0004;
        public static final int Button=0x7f0a0005;
        /** 
        <item name="android:layout">@layout/preference_holo</item>
        <item name="android:widgetLayout">@layout/preference_checkbox</item>
        
         */
        public static final int CheckBoxPreference=0x7f0a0006;
        public static final int CreditsContent=0x7f0a0007;
        public static final int CreditsTitle=0x7f0a0008;
        public static final int DetailContainerStyle=0x7f0a0009;
        public static final int DialogAnimation=0x7f0a000a;
        public static final int DialogBaseTheme=0x7f0a000b;
        public static final int DialogTheme=0x7f0a000c;
        public static final int LicenseContent=0x7f0a000d;
        public static final int LicenseTitle=0x7f0a000e;
        public static final int OnOffTextAppearance=0x7f0a000f;
        public static final int PurchaseDialogTheme=0x7f0a0010;
        public static final int SetTimeContainerStyle=0x7f0a0011;
        public static final int SyncProgress=0x7f0a0012;
        public static final int WeekdaySelectorItem=0x7f0a0013;
        public static final int Widget_Holo_CompoundButton_Switch=0x7f0a0014;
        public static final int dialpad=0x7f0a0015;
        public static final int dialpad_ampm=0x7f0a0016;
        public static final int label=0x7f0a0017;
        public static final int medium_bold=0x7f0a0018;
        public static final int medium_light=0x7f0a0019;
        public static final int textStyle=0x7f0a001a;
        public static final int textStyle_Large=0x7f0a001b;
    }
}
